// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuZG-GkWbh9dpMX6_t4ccfxiab_8RqLuE',
    appId: '1:508168425543:web:ad3f82ff1a6ae6f861a162',
    messagingSenderId: '508168425543',
    projectId: 'trackin-d4a84',
    authDomain: 'trackin-d4a84.firebaseapp.com',
    storageBucket: 'trackin-d4a84.firebasestorage.app',
    measurementId: 'G-7TXVTKYGNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3NPGePsExh5Pob2nFt9GpEV9CMTcZUNg',
    appId: '1:508168425543:android:ec88820aaf4f798961a162',
    messagingSenderId: '508168425543',
    projectId: 'trackin-d4a84',
    storageBucket: 'trackin-d4a84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaCP6cTkF42ggOpQRG4yHg3IdVd5qEXXs',
    appId: '1:508168425543:ios:36f1f692e343236861a162',
    messagingSenderId: '508168425543',
    projectId: 'trackin-d4a84',
    storageBucket: 'trackin-d4a84.firebasestorage.app',
    iosBundleId: 'com.example.trackIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaCP6cTkF42ggOpQRG4yHg3IdVd5qEXXs',
    appId: '1:508168425543:ios:36f1f692e343236861a162',
    messagingSenderId: '508168425543',
    projectId: 'trackin-d4a84',
    storageBucket: 'trackin-d4a84.firebasestorage.app',
    iosBundleId: 'com.example.trackIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuZG-GkWbh9dpMX6_t4ccfxiab_8RqLuE',
    appId: '1:508168425543:web:85fe55494381ef4a61a162',
    messagingSenderId: '508168425543',
    projectId: 'trackin-d4a84',
    authDomain: 'trackin-d4a84.firebaseapp.com',
    storageBucket: 'trackin-d4a84.firebasestorage.app',
    measurementId: 'G-PX10K9SXJG',
  );
}
